### ISSUE TITLE
MSM still saves backups for stopped servers

### ISSUE THREAD

**Issue by LeoDJ** [msmhq/msm#347] opened 2016-11-18 00:08 UTC
I have a server with a world size of 300MB. This server was stopped some months ago.

Now I was notified, that my free space was running low and I narrowed it down to the msm archive directory. 
MSM has been creating full backups of this server every day. Not even differential backups.

Is this normal behaviour and if so, how can I stop it?

PS: please implement differential backups if you find the time

**Comment by MobiusTesseract** [comment] 2016-12-06 12:38
Differential backups are already implemented, look for the rdiff and rsync backup options in /etc/msm.conf

However, I believe that backups of all servers are intended behavior, since the backup script would have no way of knowing whether a given server was started and stopped again between backups. A per-server flag would be nice though.

That said, if you are taking world backups and not full server ones, you could deactivate every world in the server in question and just remember to activate them again if you ever want to run it in the future.

**Comment by endofcake** [comment] 2017-02-15 00:51
I believe this question was answered, so it's ok to close it. 
Rdiff backups are configure here:
https://github.com/msmhq/msm/blob/master/msm.conf#L68:L85

**Closed by endofcake** 2017-02-15 00:51 UTC
