### ISSUE TITLE
MC Linux Server won't start

### ISSUE THREAD

**Issue by Milesbreen** [msmhq/msm#407] opened 2020-10-02 22:25 UTC
Hello! Every time I try to start my server, it goeds through the commands but then when I look for status, it says it is stopped. Anyone know what is wrong.
These are the commands:

root@minecraft:~# /usr/local/bin/msm DarkGecko start
Test
Maintaining world symbolic links... Done.
Synchronising flagged worlds on disk to RAM... Done.
Starting server...... Done.
root@minecraft:~# /usr/local/bin/msm DarkGecko status
Server "DarkGecko" is stopped.

**Comment by renderorange** [comment] 2020-10-04 04:02
Hi, I imagine the issue is java isn’t starting because of invalid variables.

In msm.conf, try editing line 165 for `DEFAULT_INVOCATION` to remove:
`-XX:+UseConcMarkSweepGC -XX:+CMSIncrementalPacing -XX:+AggressiveOpts`

The whole line should just be:
`DEFAULT_INVOCATION="java -Xms{RAM}M -Xmx{RAM}M -jar {JAR} nogui"`

Issue #402 fixes that so it will start up correctly.

**Comment by endofcake** [comment] 2020-12-03 09:25
PR merged.

**Closed by endofcake** 2020-12-03 09:25 UTC
