### ISSUE TITLE
1.12 support?

### ISSUE THREAD

**Issue by sonic2005** [msmhq/msm#355] opened 2017-06-20 11:40 UTC
Hello, I tried creating a 1.12 server with MSM but it seems to not work. I used this link for my server.jar:
https://s3.amazonaws.com/Minecraft.Download/versions/1.12/minecraft_server.1.12.jar. When I type "sudo msm 1-12(my server name) start", it says starting server... and then after a minute or so, Done comes out. However, my server isn't started. There are no new worlds or crash-reports generated.
Please help... Is it a problem of the server.jar link?

**Comment by kjkazinski** [comment] 2017-06-20 14:23
Did you accept the license agreement?

**Comment by morbeo** [comment] 2017-06-20 20:44
Can you provide more information like what OS are you using, bash version and so on?

**Comment by endofcake** [comment] 2017-06-21 08:24
No issues running 1.12, you do need to accept license agreement though.
```
cd <your-server-directory>
cat eula.txt
```
to check if it's accepted.

**Comment by sonic2005** [comment] 2017-06-21 09:44
Eula.txt didn't;t get generated at all. I'm using AWS ubuntu and I'm connecting form my Mac. I had no problem running other versions.

**Comment by endofcake** [comment] 2017-06-21 10:13
Not sure what exactly happened on your system, but you should be able to get past the EULA stage by running
```
echo "eula=true" > eula.txt
```
in your server directory.

**Comment by sonic2005** [comment] 2017-06-21 10:19
Doesn't work... Seems like it's not the problem of the Eula. can anyone give me a different link for the 1.12.jar or tell me another way to fix this?

**Comment by endofcake** [comment] 2017-06-21 10:25
Have you checked the server logs? They can be found in the `logs` directory.

**Comment by sonic2005** [comment] 2017-06-21 11:02
I think I'm doing something wrong but I don't have a logs folder.
All the files and folders In my server directory is:
active, banned-ips.txt, banned-players.txt, eula.txt, ops.txt, server.jar, server.properties, white-list.txt, worldstorage. (I made the Eula.txt)

**Comment by endofcake** [comment] 2017-06-21 21:29
@sonic2005 , you need to provide more information on what exactly you did and what results you've got, because it's becoming increasingly difficult to get what went wrong in your system.

**Comment by sonic2005** [comment] 2017-06-21 23:32
Ok, I'll try my best. So, I had a jargroup named `minecraft`and it had two files. `2017-06-20-13-28-57-minecraft_server.1.11.2.jar` and `2017-06-20-13-33-13-minecraft_server.1.12.jar`. So I did `sudo msm server create 1-12`. And then it got created. Then, I typed `sudo msm 1-12 jar minecraft 2017-06-20-13-33-13-minecraft_server.1.12.jar`. And then it said `Server "1-12" is now using "/opt/msm/jars/minecraft/2017-06-20-13-33-13-minecraft_server.1.12.jar".` So I just did `sudo msm 1-12 start`. Then the terminal gave `Maintaining world symbolic links... Done.
Synchronising flagged worlds on disk to RAM... Done.
Starting server...`this, and after 30 seconds, it gave `Maintaining world symbolic links... Done.
Synchronising flagged worlds on disk to RAM... Done.
Starting server... Done.` this. But the server wasn't running. In the 1-12 directory, I only had `active, banned-ips.txt, banned-players.txt, eula.txt, ops.txt, server.jar, server.properties, white-list.txt, worldstorage. (I made the Eula.txt)` I wish I provided the needed info. Please tell me if I need to provide more things. I know it's a problem of the 1-12 server because other servers work properly.

**Comment by sheamon** [comment] 2017-06-23 04:59
I am having this same issue. 1.11.X is working fine but 1.12 will not start. Logs don't show anything and it gives the appearance that everything is running properly. I used an existing world and even created a new one. When reverting back to the 1.11 jar it runs fine. Java version is 1.7.0_131.

**Comment by sonic2005** [comment] 2017-06-23 07:12
Sorry, but how do I update my JRE? I'm using Redhat and I used yum to get the package. When I type
`java -version`, `openjdk version "1.8.0_131" OpenJDK Runtime Environment (build 1.8.0_131-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)` this comes out. however, my server still doesn't work. Please help!

**Comment by M-D-M** [comment] 2017-06-23 15:35
Confirmed from Mojang -- Java 1.8 is needed for 1.12 (mentions the client but I think the server requires the same version): https://help.mojang.com/customer/en/portal/articles/325948-minecraft-system-requirements

Closing as this isn't a msm issue but a minecraft jar issue.

**Closed by M-D-M** 2017-06-23 15:35 UTC
